// init/data.js
export const plants = [
  {
    plant_id: "aloe_vera",
    plant_name: "Aloe Vera",
    scientific_name: "Aloe barbadensis miller",
    description:
      "A hardy succulent known for healing gel and minimal watering needs.",
    category: ["medicinal", "indoor", "low_maintenance"],
    tags: ["medicinal", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434696/david-docil-r1EqKGkGMKc-unsplash_i0anhl.jpg",
    care_cycle: {
      watering: {
        display: "2–3 weeks",
        days: 18,
        method: "light",
        steps: [
          "Water lightly around the base",
          "Avoid overwatering",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "12 months",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining cactus mix soil",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "light",
        steps: [
          "Use diluted liquid fertilizer",
          "Apply at 1/4 strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "6 months",
        days: 180,  
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Well-draining sandy soil",
      soil_used: "Cactus mix",
    },
    benefits: ["Heals burns", "Easy care", "Air purification"],
    pet_friendly: false,
    toxic: true,
    light_required: "bright_indirect",
    care_difficulty: "easy",
    common_issues: ["Root rot", "Soft leaves"],
  },
  {
    plant_id: "money_plant",
    plant_name: "Money Plant",
    scientific_name: "Epipremnum aureum",
    description:
      "Fast-growing indoor vine known for prosperity and air cleaning.",
    category: ["indoor", "hanging", "good_luck"],
    tags: ["vastu friendly", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434886/fuseviews-9hfSqabj6Wc-unsplash_fu5yvu.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "10 months",
        days: 300,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "2 months",
        days: 60,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Moist well-draining soil",
      soil_used: "Potting mix",
    },
    benefits: ["Improves air quality", "Decorative look"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_bright_indirect",
    care_difficulty: "easy",
    common_issues: ["Yellow leaves", "Leggy growth"],
  },
  {
    plant_id: "snake_plant",
    plant_name: "Snake Plant",
    scientific_name: "Sansevieria trifasciata",
    description: "Tough low-light plant that releases oxygen at night.",
    category: ["indoor", "low_light", "low_maintenance"],
    tags: ["low light", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434932/abhinav-bhardwaj-VB36aYWsIUQ-unsplash_n0agmw.jpg",
    care_cycle: {
      watering: {
        display: "2 weeks",
        days: 14,
        method: "light",
        steps: [
          "Water lightly around the base",
          "Avoid overwatering",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "18 months",
        days: 540,
        method: "check",
        steps: [
          "Check if roots are crowding",
          "Look for roots growing through drainage holes",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "light",
        steps: [
          "Use diluted liquid fertilizer",
          "Apply at 1/4 strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "When damaged",
        days: 120,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Loose fast-draining soil",
      soil_used: "Succulent mix",
    },
    benefits: ["Improves sleep air", "Very hardy"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_medium",
    care_difficulty: "easy",
    common_issues: ["Root rot", "Wrinkled leaves"],
  },
  {
    plant_id: "areca_palm",
    plant_name: "Areca Palm",
    scientific_name: "Dypsis lutescens",
    description: "Elegant palm that humidifies indoor spaces.",
    category: ["indoor", "pet_friendly"],
    tags: ["pet friendly", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434755/soyoung-han-NlDou0x_W3E-unsplash_o2govp.jpg",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "3 months",
        days: 90,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Light moisture retaining soil",
      soil_used: "Peat mix",
    },
    benefits: ["Pet safe", "Humidifies air"],
    pet_friendly: true,
    toxic: false,
    light_required: "bright_indirect",
    care_difficulty: "moderate",
    common_issues: ["Brown tips", "Dry air stress"],
  },
  {
    plant_id: "tulsi",
    plant_name: "Tulsi",
    scientific_name: "Ocimum tenuiflorum",
    description: "Sacred medicinal herb used in Ayurveda.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["medicinal", "vastu friendly"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434936/sujay-paul-clMuW2_iDZo-unsplash_tbhhk3.jpg",
    care_cycle: {
      watering: {
        display: "2 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "8 months",
        days: 240,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "organic",
        steps: [
          "Use organic compost or worm castings",
          "Apply as top dressing",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Monthly",
        days: 30,
        method: "pinch",
        steps: [
          "Pinch back growing tips",
          "Encourages bushier growth",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile draining soil",
      soil_used: "Garden soil + compost",
    },
    benefits: ["Boosts immunity", "Reduces stress"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: ["Wilting", "Pests"],
  },
  {
    plant_id: "rose",
    plant_name: "Rose",
    scientific_name: "Rosa spp.",
    description: "Beautiful flowering shrub with fragrant blooms.",
    category: ["flowering", "outdoor"],
    tags: ["decorative", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434912/Image_fkjzpv.png",
    care_cycle: {
      watering: {
        display: "3 times a week",
        days: 2,
        method: "deep",
        steps: [
          "Deep soak until water drains freely",
          "Ensure soil is fully saturated",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "15 days",
        days: 15,
        method: "heavy",
        steps: [
          "Use full-strength fertilizer",
          "Heavy feeders need regular feeding",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Seasonally",
        days: 90,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Rich fertile soil",
      soil_used: "Garden soil + manure",
    },
    benefits: ["Beautifies space", "Boosts mood"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "advanced",
    common_issues: ["Black spots", "Aphids"],
  },
  {
    plant_id: "mint",
    plant_name: "Mint",
    scientific_name: "Mentha",
    description: "Fast-growing aromatic culinary herb.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "fast growing"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434855/mint_jnllom.png",
    care_cycle: {
      watering: {
        display: "2 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "6 months",
        days: 180,
        method: "division",
        steps: [
          "Divide root ball into sections",
          "Plant each division separately",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Frequently",
        days: 5,
        method: "pinch",
        steps: [
          "Pinch back growing tips",
          "Encourages bushier growth",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Moist fertile soil",
      soil_used: "Garden soil",
    },
    benefits: ["Aids digestion", "Fresh flavor"],
    pet_friendly: true,
    toxic: false,
    light_required: "partial_sunlight",
    care_difficulty: "easy",
    common_issues: ["Overgrowth", "Wilting"],
  },
  {
    plant_id: "jasmine",
    plant_name: "Jasmine",
    scientific_name: "Jasminum",
    description: "Flowering plant with strong sweet fragrance.",
    category: ["flowering", "aromatic", "outdoor"],
    tags: ["fragrant", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434811/garry-ry-XdzbSNEVrQk-unsplash_gydwoc.jpg",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "After flowering",
        days: 120,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Loose fertile soil",
      soil_used: "Garden soil + compost",
    },
    benefits: ["Pleasant fragrance", "Garden beauty"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: ["Bud drop", "Pests"],
  },
  {
    plant_id: "peace_lily",
    plant_name: "Peace Lily",
    scientific_name: "Spathiphyllum",
    description:
      "Elegant indoor plant with white flowers and air-cleaning power.",
    category: ["indoor", "flowering"],
    tags: ["air purifying", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434896/ashlee-marie-j_BRZG1e_Bw-unsplash_jxzom8.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "bottom",
        steps: [
          "Place pot in water tray",
          "Let roots absorb from bottom",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "When leaves die",
        days: 120,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: { characteristics: "Moist rich soil", soil_used: "Potting mix" },
    benefits: ["Purifies air", "Beautiful blooms"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_medium",
    care_difficulty: "moderate",
    common_issues: ["Drooping leaves", "Brown tips"],
  },
  {
    plant_id: "lemon_tree",
    plant_name: "Lemon Plant",
    scientific_name: "Citrus limon",
    description: "Fruit-bearing citrus plant with fragrant flowers.",
    category: ["fruit", "outdoor"],
    tags: ["edible fruit", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434831/lemon_pq3szq.png",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "deep",
        steps: [
          "Deep soak until water drains freely",
          "Ensure soil is fully saturated",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "2 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "heavy",
        steps: [
          "Use full-strength fertilizer",
          "Heavy feeders need regular feeding",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Seasonally",
        days: 90,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Well-draining fertile soil",
      soil_used: "Garden soil + compost",
    },
    benefits: ["Fresh lemons", "Garden freshness"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: ["Leaf curl", "Fruit drop"],
  },
];
