// init/data.js
export const plants = [
  {
    plant_id: "aloe_vera",
    plant_name: "Aloe Vera",
    scientific_name: "Aloe barbadensis miller",
    description:
      "A hardy succulent known for healing gel and minimal watering needs.",
    category: ["medicinal", "indoor", "low_maintenance"],
    tags: ["medicinal", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434696/david-docil-r1EqKGkGMKc-unsplash_i0anhl.jpg",
    care_cycle: {
      watering: {
        display: "2–3 weeks",
        days: 18,
        method: "light",
        steps: [
          "Water lightly around the base",
          "Avoid overwatering",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "12 months",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining cactus mix soil",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "light",
        steps: [
          "Use diluted liquid fertilizer",
          "Apply at 1/4 strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "6 months",
        days: 180,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy well-draining",
      soil_used: "Cactus mix",
    },
    benefits: ["Heals burns", "Easy care", "Air purification"],
    pet_friendly: false,
    toxic: true,
    light_required: "bright_indirect",
    care_difficulty: "easy",
    common_issues: ["Root rot", "Soft leaves"],
  },
  {
    plant_id: "money_plant",
    plant_name: "Money Plant",
    scientific_name: "Epipremnum aureum",
    description:
      "Fast-growing indoor vine known for prosperity and air cleaning.",
    category: ["indoor", "hanging", "good_luck"],
    tags: ["vastu friendly", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434886/fuseviews-9hfSqabj6Wc-unsplash_fu5yvu.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "10 months",
        days: 300,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "2 months",
        days: 60,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Moist well-draining",
      soil_used: "Potting mix",
    },
    benefits: ["Improves air quality", "Decorative look"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_bright_indirect",
    care_difficulty: "easy",
    common_issues: ["Yellow leaves", "Leggy growth"],
  },
  {
    plant_id: "snake_plant",
    plant_name: "Snake Plant",
    scientific_name: "Sansevieria trifasciata",
    description: "Tough low-light plant that releases oxygen at night.",
    category: ["indoor", "low_light", "low_maintenance"],
    tags: ["low light", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434932/abhinav-bhardwaj-VB36aYWsIUQ-unsplash_n0agmw.jpg",
    care_cycle: {
      watering: {
        display: "2 weeks",
        days: 14,
        method: "light",
        steps: [
          "Water lightly around the base",
          "Avoid overwatering",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "18 months",
        days: 540,
        method: "check",
        steps: [
          "Check if roots are crowding",
          "Look for roots growing through drainage holes",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "light",
        steps: [
          "Use diluted liquid fertilizer",
          "Apply at 1/4 strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "When damaged",
        days: 120,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Fast-draining loose",
      soil_used: "Succulent mix",
    },
    benefits: ["Improves sleep air", "Very hardy"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_medium",
    care_difficulty: "easy",
    common_issues: ["Root rot", "Wrinkled leaves"],
  },
  {
    plant_id: "areca_palm",
    plant_name: "Areca Palm",
    scientific_name: "Dypsis lutescens",
    description: "Elegant palm that humidifies indoor spaces.",
    category: ["indoor", "pet_friendly"],
    tags: ["pet friendly", "air purifying"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434755/soyoung-han-NlDou0x_W3E-unsplash_o2govp.jpg",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "3 months",
        days: 90,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Moisture-retaining light",
      soil_used: "Peat mix",
    },
    benefits: ["Pet safe", "Humidifies air"],
    pet_friendly: true,
    toxic: false,
    light_required: "bright_indirect",
    care_difficulty: "moderate",
    common_issues: ["Brown tips", "Dry air stress"],
  },
  {
    plant_id: "tulsi",
    plant_name: "Tulsi",
    scientific_name: "Ocimum tenuiflorum",
    description: "Sacred medicinal herb used in Ayurveda.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["medicinal", "vastu friendly"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434936/sujay-paul-clMuW2_iDZo-unsplash_tbhhk3.jpg",
    care_cycle: {
      watering: {
        display: "2 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "8 months",
        days: 240,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "organic",
        steps: [
          "Use organic compost or worm castings",
          "Apply as top dressing",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Monthly",
        days: 30,
        method: "pinch",
        steps: [
          "Pinch back growing tips",
          "Encourages bushier growth",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Soil + compost",
    },
    benefits: ["Boosts immunity", "Reduces stress"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: ["Wilting", "Pests"],
  },
  {
    plant_id: "rose",
    plant_name: "Rose",
    scientific_name: "Rosa spp.",
    description: "Beautiful flowering shrub with fragrant blooms.",
    category: ["flowering", "outdoor"],
    tags: ["decorative", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434912/Image_fkjzpv.png",
    care_cycle: {
      watering: {
        display: "3 times a week",
        days: 2,
        method: "deep",
        steps: [
          "Deep soak until water drains freely",
          "Ensure soil is fully saturated",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "15 days",
        days: 15,
        method: "heavy",
        steps: [
          "Use full-strength fertilizer",
          "Heavy feeders need regular feeding",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Seasonally",
        days: 90,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Rich fertile",
      soil_used: "Soil + manure",
    },
    benefits: ["Beautifies space", "Boosts mood"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "advanced",
    common_issues: ["Black spots", "Aphids"],
  },
  {
    plant_id: "mint",
    plant_name: "Mint",
    scientific_name: "Mentha",
    description: "Fast-growing aromatic culinary herb.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "fast growing"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434855/mint_jnllom.png",
    care_cycle: {
      watering: {
        display: "2 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "6 months",
        days: 180,
        method: "division",
        steps: [
          "Divide root ball into sections",
          "Plant each division separately",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Frequently",
        days: 5,
        method: "pinch",
        steps: [
          "Pinch back growing tips",
          "Encourages bushier growth",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Moist fertile",
      soil_used: "Garden soil",
    },
    benefits: ["Aids digestion", "Fresh flavor"],
    pet_friendly: true,
    toxic: false,
    light_required: "partial_sunlight",
    care_difficulty: "easy",
    common_issues: ["Overgrowth", "Wilting"],
  },
  {
    plant_id: "jasmine",
    plant_name: "Jasmine",
    scientific_name: "Jasminum",
    description: "Flowering plant with strong sweet fragrance.",
    category: ["flowering", "aromatic", "outdoor"],
    tags: ["fragrant", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434811/garry-ry-XdzbSNEVrQk-unsplash_gydwoc.jpg",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "moderate",
        steps: [
          "Water thoroughly until it drains",
          "Allow soil to dry between waterings",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replace old soil with fresh mix",
          "Can use same size pot",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "After flowering",
        days: 120,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Loose fertile",
      soil_used: "Soil + compost",
    },
    benefits: ["Pleasant fragrance", "Garden beauty"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: ["Bud drop", "Pests"],
  },
  {
    plant_id: "peace_lily",
    plant_name: "Peace Lily",
    scientific_name: "Spathiphyllum",
    description:
      "Elegant indoor plant with white flowers and air-cleaning power.",
    category: ["indoor", "flowering"],
    tags: ["air purifying", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434896/ashlee-marie-j_BRZG1e_Bw-unsplash_jxzom8.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "bottom",
        steps: [
          "Place pot in water tray",
          "Let roots absorb from bottom",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "2 months",
        days: 60,
        method: "balanced",
        steps: [
          "Use balanced liquid fertilizer",
          "Apply at recommended strength",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "When leaves die",
        days: 120,
        method: "trim",
        steps: [
          "Remove dead or brown leaves",
          "Light maintenance trimming",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: { characteristics: "Moist rich", soil_used: "Potting mix" },
    benefits: ["Purifies air", "Beautiful blooms"],
    pet_friendly: false,
    toxic: true,
    light_required: "low_to_medium",
    care_difficulty: "moderate",
    common_issues: ["Drooping leaves", "Brown tips"],
  },
  {
    plant_id: "lemon_tree",
    plant_name: "Lemon Plant",
    scientific_name: "Citrus limon",
    description: "Fruit-bearing citrus plant with fragrant flowers.",
    category: ["fruit", "outdoor"],
    tags: ["edible fruit", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1772434831/lemon_pq3szq.png",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "deep",
        steps: [
          "Deep soak until water drains freely",
          "Ensure soil is fully saturated",
          "Check soil moisture before watering",
          "Reduce watering in winter months",
        ],
      },
      repotting: {
        display: "2 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Use pot 2 inches larger than current",
          "Ensure good drainage",
          "Use well-draining soil mix",
          "Best done in spring season",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "heavy",
        steps: [
          "Use full-strength fertilizer",
          "Heavy feeders need regular feeding",
          "Apply during growing season (spring/summer)",
          "Reduce or skip in winter",
        ],
      },
      pruning: {
        display: "Seasonally",
        days: 90,
        method: "shape",
        steps: [
          "Shape to maintain desired form",
          "Cut above leaf nodes",
          "Use clean, sharp tools",
          "Dispose of diseased material properly",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Soil + compost",
    },
    benefits: ["Fresh lemons", "Garden freshness"],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: ["Leaf curl", "Fruit drop"],
  },
  // ── NEW PLANTS FROM JSON ────────────────────────────────────────────────────
  {
    plant_id: "marigold",
    plant_name: "Marigold",
    scientific_name: "Tagetes spp.",
    description:
      "Fast-growing warm-season annual with vibrant golden-yellow and orange blooms, widely grown in Indian balcony containers. Naturally repels aphids, whiteflies, and soil nematodes.",
    category: ["flowering", "outdoor", "low_maintenance"],
    tags: ["decorative", "pest repellent"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773643265/marigold_zntwjl.jpg",
    care_cycle: {
      watering: {
        display: "Every 3–4 days",
        days: 3,
        method: "moderate",
        steps: [
          "Water when the top 1 to 2 inches of soil feel dry — marigolds prefer consistently moist but never soggy soil",
          "Always water at the base of the plant; wetting the foliage promotes powdery mildew and other fungal diseases",
          "In peak summer heat, container-grown plants may need water every 2 days — check soil more frequently during hot spells",
          "Reduce watering frequency in autumn as growth and temperature naturally slow down",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replant into fresh potting mix at the start of each growing season in spring",
          "French marigolds suit 6 to 8-inch pots; larger African types need at least a 10-inch pot with multiple drainage holes",
          "Use a 50% compost, 30% garden soil, 20% perlite or coarse sand mix for good moisture retention without waterlogging",
          "Terracotta pots work well — their porous walls help regulate soil moisture and temperature",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "light",
        steps: [
          "Marigolds are not heavy feeders — too much nitrogen produces lush foliage but drastically reduces flower production",
          "Apply a balanced fertilizer with an NPK of 10-10-10 once a month during the growing season",
          "Organic options like mustard cake liquid or banana peel fertilizer every 15 to 20 days work very well",
          "Never use high-nitrogen formulas — they actively inhibit flowering in this plant",
        ],
      },
      pruning: {
        display: "Every 2 weeks",
        days: 14,
        method: "pinch",
        steps: [
          "Deadhead spent blooms by snipping or pinching promptly — this is the single most effective way to keep marigolds flowering all season",
          "Pinch growing tips of young plants to encourage bushy, branching growth rather than tall, leggy stems",
          "Remove any dry, wilted stems and leaves as soon as they appear",
          "Shear plants back by one-third in midsummer if they become leggy to trigger a fresh flush of flowers",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Compost + soil mix",
    },
    benefits: [
      "Continuous bright colour from summer through winter",
      "Natural pest deterrent — repels nematodes, aphids, and mosquitoes",
      "Widely used in Indian religious and festive garlands",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Powdery mildew from wet foliage",
      "Leggy, few flowers from excess nitrogen",
    ],
  },
  {
    plant_id: "chili_pepper",
    plant_name: "Chili Pepper",
    scientific_name: "Capsicum annuum",
    description:
      "Warm-season fruiting plant native to the Americas. Compact varieties produce prolific yields of colourful fiery fruits in containers, serving as both a practical kitchen crop and striking ornamental display.",
    category: ["fruit", "outdoor"],
    tags: ["edible", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644053/chilli_ol3ox8.jpg",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Check soil moisture by inserting a finger 2 to 4 inches deep — water when soil feels dry at that depth",
          "Water deeply and thoroughly at the base of the plant until it drains freely from the bottom drainage holes",
          "Container-grown chilis are thirsty in summer heat — check daily and water whenever the soil dries out",
          "Avoid getting water on the foliage — water the root zone only to reduce the risk of fungal disease",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Plant or repot into a container at least 20 to 40 cm deep and wide to support the deep root system",
          "Use a fertile, well-draining potting mix — adding compost or perlite to standard potting mix significantly improves aeration",
          "Repot into a slightly larger container each season to prevent the plant from becoming root-bound and stressed",
          "Best done at the start of spring when temperatures are rising and risk of cold nights has passed",
        ],
      },
      fertilizing: {
        display: "Every 2 weeks",
        days: 14,
        method: "balanced",
        steps: [
          "Begin feeding with a balanced vegetable fertilizer (5-10-5 or similar NPK) from the moment the first flowers appear",
          "Feed every two weeks during the active growing and fruiting season — chilis are hungry, fast-producing plants",
          "Switch to a potassium-rich, lower-nitrogen formula once fruits begin to set to support healthy fruit development",
          "Reduce feeding in late summer as the harvest season ends and stop completely during winter",
        ],
      },
      pruning: {
        display: "Monthly",
        days: 30,
        method: "pinch",
        steps: [
          "Pinch out the central growing tip when the plant reaches 15 to 20 cm tall to encourage bushy, branching growth",
          "Never remove more than one-third of the plant at any time to avoid weakening its overall vigour",
          "Harvest ripe chilis by cutting the stem cleanly — regular harvesting stimulates the plant to produce more fruit",
          "Remove any dead, diseased, or yellowing leaves promptly to maintain plant vigour",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Potting mix + compost",
    },
    benefits: [
      "Prolific edible harvest of fresh chilis ideal for Indian cooking",
      "Compact varieties suit any sized balcony container",
      "Highly ornamental when loaded with colourful ripening fruit of different stages",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: [
      "Leaf drop from inconsistent watering or temperature swings",
      "Aphid and whitefly on new buds",
    ],
  },
  {
    plant_id: "hibiscus",
    plant_name: "Hibiscus",
    scientific_name: "Hibiscus rosa-sinensis",
    description:
      "Vigorous tropical flowering shrub producing large trumpet-shaped blooms up to 8 inches wide. Known as Gurhal or China Rose, it is iconic to Indian homes and valued in Ayurveda for its hair-strengthening properties.",
    category: ["flowering", "outdoor", "medicinal"],
    tags: ["decorative", "medicinal"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644089/hibiscus_t3cze9.jpg",
    care_cycle: {
      watering: {
        display: "Daily in summer",
        days: 2,
        method: "moderate",
        steps: [
          "Check soil daily — if the top 1 to 2 inches feel dry, water thoroughly until excess drains freely from the bottom",
          "Container-grown hibiscus may need daily watering in peak summer heat — the more sun it receives, the more water it needs",
          "Never allow the plant to sit in standing water in the saucer — this causes root rot rapidly",
          "Reduce watering significantly in winter when the plant is resting — water only when soil is dry to the touch",
        ],
      },
      repotting: {
        display: "Every 2–3 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Hibiscus blooms best when slightly root-bound — repot only when roots visibly emerge from drainage holes or growth stalls",
          "Move into a pot only one size larger — overpotting leads to waterlogged soil and poor flowering",
          "Use a lightweight, fertile, well-draining potting mix; add perlite or vermiculite for improved aeration",
          "Water the plant thoroughly the day before repotting to minimise transplant stress on the root ball",
        ],
      },
      fertilizing: {
        display: "Every 2 weeks",
        days: 14,
        method: "balanced",
        steps: [
          "Hibiscus are heavy feeders — use a fertilizer with a high potassium and low phosphorus content (NPK 17-5-24 is ideal for tropical types)",
          "Apply every two weeks from spring through autumn to support continuous bloom production",
          "Always water the soil before applying fertilizer to avoid root burn",
          "Stop all feeding in winter — fertilizing during dormancy promotes weak, tender growth vulnerable to pests and cold",
        ],
      },
      pruning: {
        display: "Early spring",
        days: 90,
        method: "shape",
        steps: [
          "Cut back by about half in early spring to maintain shape and stimulate new wood — hibiscus blooms only on new wood",
          "Remove all dead, crossing, or diseased branches first, then trim remaining stems back by one-third",
          "Pinch back growing tips throughout summer to encourage a bushy, compact, floriferous plant",
          "Remove spent flowers throughout the season to keep the plant tidy and maintain energy for new bloom production",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Potting mix + perlite",
    },
    benefits: [
      "Prolific large tropical blooms throughout the entire growing season",
      "Flowers and leaves used in Ayurvedic hair care and herbal preparations",
      "Compact varieties suited to any sunny balcony container",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: [
      "Bud drop from temperature changes or irregular watering",
      "Aphids and spider mites on new growth",
    ],
  },
  {
    plant_id: "geranium",
    plant_name: "Geranium",
    scientific_name: "Pelargonium × hortorum",
    description:
      "Classic tender perennial flowering plant, one of the most enduringly popular balcony plants in the world. Blooms prolifically from mid-spring to the first frost in shades of red, pink, salmon, coral, white, and purple.",
    category: ["flowering", "outdoor"],
    tags: ["decorative", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644120/geranium_huextu.jpg",
    care_cycle: {
      watering: {
        display: "Twice a week",
        days: 3,
        method: "moderate",
        steps: [
          "Allow the top 1 to 2 inches of soil to dry out before watering — geraniums prefer drier conditions over wet soil",
          "Water containers with about half a litre per plant twice a week; always check soil moisture at 2 to 3 cm depth before watering",
          "Water at soil level and avoid wetting the foliage — wet leaves promote mildew and fungal disease",
          "Reduce watering substantially in winter — water only when leaves show very early signs of drooping",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Repot in spring into fresh potting mix — geraniums bloom best when slightly pot-bound, so move into a pot only 1 to 2 inches larger",
          "Use a peat-free, well-draining multi-purpose compost or a dedicated pelargonium compost mix",
          "Ensure the pot has adequate drainage holes — geraniums are very susceptible to root rot in waterlogged soil",
          "Pinch back stems after repotting to encourage compact, branching growth for the season ahead",
        ],
      },
      fertilizing: {
        display: "Every 10–14 days",
        days: 14,
        method: "balanced",
        steps: [
          "Apply a balanced liquid fertilizer every 10 to 14 days in spring as per the RHS recommendation for vigorous growth",
          "Feed every two weeks at half strength using a water-soluble balanced formula (10-10-10 or 20-20-20)",
          "Switch to a high-potassium (tomato-type) fertilizer once flower buds form to support peak bloom performance",
          "Stop all fertilizing in autumn and winter when the plant is dormant",
        ],
      },
      pruning: {
        display: "Regularly",
        days: 14,
        method: "pinch",
        steps: [
          "Deadhead spent flower heads by snipping just below the old flower to encourage continuous reblooming throughout the season",
          "Pinch back growing tips throughout the season to promote bushier, more compact growth and prevent legginess",
          "Cut stems back by at least two-thirds in late autumn or spring at a 45-degree angle just above a leaf node",
          "Remove yellowing leaves promptly — yellow leaves often signal overwatering or root stress",
        ],
      },
    },
    soil_type: {
      characteristics: "Well-draining fertile",
      soil_used: "Peat-free compost mix",
    },
    benefits: [
      "Long-lasting blooms from spring through first frost in an enormous range of colours",
      "Classic balcony and window box plant — among the best suited to container growing",
      "Drought-tolerant once established and low-maintenance in a sunny spot",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_to_partial_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Root rot from overwatering or compacted soil",
      "Yellow leaves from excess watering or old potting mix",
    ],
  },
  {
    plant_id: "bougainvillea",
    plant_name: "Bougainvillea",
    scientific_name: "Bougainvillea spp.",
    description:
      "Vigorous sun-loving tropical climbing shrub native to South America, one of the most iconic plants of Indian walls, terraces, and balconies. Vivid papery bracts surround tiny white true flowers. Blooms most profusely when kept slightly drought-stressed.",
    category: ["flowering", "outdoor"],
    tags: ["decorative", "fast growing"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644144/A5B75310-5282-4930-823B-DDD1A550200E_yjuczp.jpg",
    care_cycle: {
      watering: {
        display: "Every 3–4 days",
        days: 3,
        method: "deep",
        steps: [
          "Water deeply when the top 2 to 3 inches of soil are dry — allow the soil to approach dryness between waterings",
          "Bougainvillea blooms best when kept on the dry side — overwatering produces lush green growth but drastically reduces flowering",
          "In established pots, water thoroughly once a week; during extreme heat, water twice if plants show leaf stress",
          "Reduce watering significantly in winter when the plant is semi-dormant",
        ],
      },
      repotting: {
        display: "Every 2–3 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Bougainvillea blooms best when pot-bound — repot every 2 to 3 years only when roots are visibly crowded",
          "Move to a pot just one size larger; too large a container leads to wet soil and reduced flowering",
          "Use a well-draining potting mix — add perlite or coarse sand to standard potting soil for improved drainage",
          "Handle the root ball with great care — bougainvillea has fragile roots that are easily damaged during repotting",
        ],
      },
      fertilizing: {
        display: "Every 2 weeks",
        days: 14,
        method: "balanced",
        steps: [
          "Apply a high-potassium, low-nitrogen fertilizer every two weeks during the growing season — excess nitrogen promotes leaves over flowers",
          "A bloom-booster formula (low nitrogen such as 5-10-10 or 6-30-30) applied fortnightly in spring and summer produces spectacular results",
          "Always water the soil before applying any fertilizer to prevent root burn",
          "Stop fertilizing in winter when the plant is resting — resume in late winter as new growth begins",
        ],
      },
      pruning: {
        display: "After flowering",
        days: 90,
        method: "shape",
        steps: [
          "Prune back all long flowering stems by one-third to one-half immediately after each flowering cycle ends",
          "Bougainvillea blooms on new growth — regular pruning directly stimulates the new shoots that carry the next flush of bracts",
          "Hard prune in early spring to shape the plant and control size — this is the most important seasonal maintenance task",
          "Always wear thick gloves when pruning — the stems have sharp thorns that can cause painful injury",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy fast-draining",
      soil_used: "Potting mix + sand",
    },
    benefits: [
      "Spectacular papery bracts in vivid colours throughout a long blooming season",
      "Drought-tolerant once established — ideal for hot Indian balconies in summer",
      "One of the most iconic ornamental plants of Indian homes and outdoor spaces",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: [
      "Bract drop from overwatering or root disturbance",
      "No flowers from excess nitrogen or low sunlight",
    ],
  },
  {
    plant_id: "curry_leaf",
    plant_name: "Curry Leaf",
    scientific_name: "Murraya koenigii",
    description:
      "Fast-growing aromatic evergreen tree native to India and Sri Lanka. Known as Kadi Patta, it is an essential culinary plant in South and Southeast Asian cooking, also documented in Ayurvedic medicine for digestion support and hair strengthening.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "medicinal"],
    image_name: "curry_leaf",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water deeply but infrequently — allow the top 3 to 5 cm of soil to dry between waterings to prevent root rot",
          "During summer, water 2 to 3 times a week; in cooler months, reduce to once a week or less",
          "The plant tolerates underwatering far better than overwatering — when in doubt, wait another day before rewatering",
          "Use clay pots for container growing — their porous walls allow excess moisture to escape and prevent root rot",
        ],
      },
      repotting: {
        display: "Every 1–2 years",
        days: 365,
        method: "upgrade",
        steps: [
          "Repot every 1 to 2 years in early spring — pale, dull leaves and slow growth signal that roots have exhausted their space",
          "Use a container at least 30 cm wide and deep with drainage holes to support the fast-growing root system",
          "Use a well-draining potting mix blended with perlite or coarse sand — slightly acidic soil keeps the plant healthiest",
          "Water thoroughly after repotting and place in a partially shaded spot for a few days to reduce transplant stress",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 21,
        method: "balanced",
        steps: [
          "Apply a nitrogen-rich liquid fertilizer every 3 to 4 weeks during spring and summer to support abundant leaf production",
          "In pots, use liquid fertilizer diluted to half strength every 3 weeks; flush containers with clean water every 6 to 8 weeks to prevent salt buildup",
          "Interveinal yellowing on leaves usually indicates magnesium deficiency — treat with a diluted Epsom salt solution",
          "Do not fertilize in autumn or winter when the plant is semi-dormant",
        ],
      },
      pruning: {
        display: "Annually in spring",
        days: 90,
        method: "pinch",
        steps: [
          "Prune annually in spring — cut back by at least one-third to keep the plant compact and trigger a flush of dense new leafy growth",
          "Pinch growing tips regularly throughout the season to encourage a bushy, multi-branched form",
          "Remove flower buds as soon as they appear — flowering diverts energy from leaf production and reduces harvest yield",
          "The more you harvest the leaves, the bushier the plant becomes — regular harvesting is itself a form of productive pruning",
        ],
      },
    },
    soil_type: {
      characteristics: "Aerated well-draining",
      soil_used: "Potting mix + perlite",
    },
    benefits: [
      "Essential aromatic culinary herb in South Indian and Southeast Asian cooking",
      "Ayurvedic uses for digestion support, blood sugar regulation, and hair strengthening",
      "Compact, productive, and thrives on a sunny Indian balcony in a container for years",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: [
      "Yellow leaves from magnesium deficiency",
      "Mealybugs on stems — treat with neem oil",
    ],
  },
  {
    plant_id: "coriander",
    plant_name: "Coriander",
    scientific_name: "Coriandrum sativum",
    description:
      "Annual aromatic herb known as Dhania or Cilantro, essential in Indian cooking for both its fresh leaves and dried seeds. A fast-growing balcony crop harvestable in 3 to 4 weeks. Prefers cool conditions and benefits from succession sowing every 3–4 weeks.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "fast growing"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644270/coriander_hiethe.jpg",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water when the top inch of soil feels dry — keep soil consistently moist, especially for young seedlings",
          "Inconsistent watering is a primary trigger for bolting — drought-stressed plants rush to produce flowers and seed",
          "Container-grown coriander on balconies dries faster than in-ground plants — check daily during summer heat",
          "Water at the base and avoid wetting foliage to reduce the risk of fungal disease in humid conditions",
        ],
      },
      repotting: {
        display: "Every season",
        days: 90,
        method: "refresh",
        steps: [
          "Coriander has a deep taproot that resents disturbance — sow seeds directly into the final container rather than transplanting",
          "Use a container at least 6 to 8 inches deep with drainage holes to accommodate the taproot properly",
          "Succession-sow fresh seeds every 3 to 4 weeks into fresh potting mix for a continuous harvest",
          "If repotting is necessary, do so on a cool day with care not to disturb the root ball",
        ],
      },
      fertilizing: {
        display: "Every 4–6 weeks",
        days: 45,
        method: "light",
        steps: [
          "Coriander is not a heavy feeder — fresh compost-enriched potting soil provides sufficient nutrition for most of the growing season",
          "If the leaves begin to yellow, apply a diluted balanced liquid fertilizer every 4 to 6 weeks during active growth",
          "Avoid high-potassium feeds — these actively encourage premature flowering at the expense of leafy growth",
          "Garden-bed grown coriander generally requires no supplemental fertilizing at all",
        ],
      },
      pruning: {
        display: "Every 1–2 weeks",
        days: 10,
        method: "pinch",
        steps: [
          "Harvest outer leaves regularly from when the plant reaches 10 to 15 cm tall — this acts as pruning and delays bolting",
          "Pinch growing tips to encourage a bushy, compact habit rather than a tall, leggy, bolt-prone one",
          "Remove any flower stalks as soon as they appear to redirect energy back into leaf production",
          "Once the plant has fully bolted, allow seeds to ripen fully before harvesting them as dried coriander seed",
        ],
      },
    },
    soil_type: {
      characteristics: "Loamy well-draining",
      soil_used: "Potting mix + compost",
    },
    benefits: [
      "Fresh leaves (dhania) are an essential garnish in Indian cooking",
      "Dried seeds are a major spice in Indian curries, chutneys, and masalas",
      "Quick-growing kitchen crop producing a harvest within 3 to 4 weeks from sowing",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "partial_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Bolting from heat or inconsistent watering",
      "Aphids on young growth",
    ],
  },
  {
    plant_id: "spider_plant",
    plant_name: "Spider Plant",
    scientific_name: "Chlorophytum comosum",
    description:
      "Fast-growing perennial houseplant with arching variegated leaves and cascading stems producing baby plantlets. Listed in NASA's Clean Air Study. Completely safe for pets and children. Works beautifully in hanging baskets on partially shaded balconies.",
    category: ["indoor", "hanging", "low_maintenance"],
    tags: ["air purifying", "pet friendly"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644302/spider_plant_q13kxg.jpg",
    care_cycle: {
      watering: {
        display: "Every 1–2 weeks",
        days: 7,
        method: "moderate",
        steps: [
          "Water when the top 2 inches of soil feel dry — spider plants tolerate drought well but prefer consistent light moisture",
          "Water thoroughly until it drains from the bottom, then allow the top layer to dry before watering again",
          "Reduce watering in autumn and winter when growth slows — allow the top inch to dry before each watering",
          "Use filtered, distilled, or rainwater where possible — spider plants are sensitive to fluoride and chlorine in tap water",
        ],
      },
      repotting: {
        display: "Every 2–3 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Spider plants prefer slightly root-bound conditions and produce more pups when snug — repot only when roots grow from drainage holes",
          "Choose a pot just 1 to 2 inches larger — overpotting leads to poor plantlet production and soggy soil",
          "Use a well-draining, peat-based potting mix blended with perlite for good aeration and drainage",
          "Water generously after repotting and keep in bright indirect light for a few days to aid recovery",
        ],
      },
      fertilizing: {
        display: "Every 4–6 weeks",
        days: 45,
        method: "light",
        steps: [
          "Feed once a month during spring and summer with a balanced water-soluble fertilizer at half strength",
          "Over-fertilizing is a common mistake — excessive feeding produces lush foliage but reduces plantlet production",
          "Too much fertilizer also leads to fluoride build-up in the soil, worsening brown leaf tips",
          "Stop all feeding in autumn and winter when the plant is resting",
        ],
      },
      pruning: {
        display: "As needed",
        days: 60,
        method: "trim",
        steps: [
          "Remove brown or yellowing leaves by cutting them cleanly at the base of the plant",
          "Trim brown leaf tips with clean scissors, following the natural pointed shape of the leaf to keep it looking neat",
          "Remove or pot up hanging pup plantlets once they have developed a small visible root cluster",
          "Wipe leaves occasionally with a damp cloth to remove dust and help the plant photosynthesize efficiently",
        ],
      },
    },
    soil_type: {
      characteristics: "Well-draining neutral",
      soil_used: "Potting mix + perlite",
    },
    benefits: [
      "Filters indoor air pollutants including formaldehyde and xylene",
      "Non-toxic and completely safe for pets and children",
      "Self-propagating — produces endless baby plantlets that can be potted and shared",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "low_to_bright_indirect",
    care_difficulty: "easy",
    common_issues: [
      "Brown tips from tap water fluoride or over-fertilizing",
      "Root rot from overwatering or poor drainage",
    ],
  },
  {
    plant_id: "portulaca",
    plant_name: "Portulaca",
    scientific_name: "Portulaca grandiflora",
    description:
      "Low-growing semi-succulent annual known as Moss Rose or Sun Plant. One of the most heat-tolerant and sun-loving flowering plants available, thriving in the intense conditions of Indian balconies. Blooms prolifically in a rainbow of colours; flowers open with sunlight and close at night.",
    category: ["flowering", "outdoor", "low_maintenance"],
    tags: ["decorative", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644332/portulaca_zf0ed9.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "light",
        steps: [
          "Portulaca stores water in its fleshy leaves and stems — it is highly drought-tolerant and prefers to dry out between waterings",
          "Water when the top 1 to 2 inches of soil feel dry — once a week in a container is generally sufficient",
          "Overwatering is the most serious threat — soggy soil causes crown and root rot almost immediately in this shallow-rooted plant",
          "In cooler months, allow the soil to approach complete dryness before rewatering",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Replant at the start of each growing season into fresh, sandy, well-draining potting mix",
          "Use a container with multiple drainage holes — portulaca is extremely sensitive to waterlogged soil",
          "Mix equal parts potting soil and coarse sand or use a cactus/succulent mix for the fast drainage this plant requires",
          "Position in the sunniest spot available on the balcony — at least 6 to 8 hours of direct sunlight is essential for blooming",
        ],
      },
      fertilizing: {
        display: "Monthly",
        days: 30,
        method: "light",
        steps: [
          "Portulaca prefers lean, low-fertility soil — over-fertilizing produces floppy foliage with very few flowers",
          "Apply a balanced water-soluble fertilizer (20-10-20 or 20-20-20) once a month during the main growing season",
          "A single application of a high-phosphorus bloom booster mid-season can extend and enhance flowering",
          "Never use high-nitrogen fertilizers — they actively reduce flower production in this plant",
        ],
      },
      pruning: {
        display: "Midsummer",
        days: 60,
        method: "trim",
        steps: [
          "Portulaca is largely self-cleaning — spent flowers drop freely without the need for regular deadheading",
          "Shear the entire plant back by up to half in midsummer if it begins to look straggly or overgrown",
          "After midsummer shearing, apply a half-strength balanced fertilizer to stimulate a fresh flush of blooms",
          "Pinch back growing tips on young plants to encourage the bushy, spreading growth habit this plant is known for",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy fast-draining",
      soil_used: "Succulent/cactus mix",
    },
    benefits: [
      "Blooms prolifically in a vibrant range of colours throughout the growing season",
      "Thrives in intense heat — one of the best choices for hot Indian balconies",
      "Self-cleaning — spent flowers fall freely with no deadheading required",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Root rot from overwatering or poor drainage",
      "Flowers won't open in low sunlight",
    ],
  },
  {
    plant_id: "lavender",
    plant_name: "Lavender",
    scientific_name: "Lavandula angustifolia",
    description:
      "Perennial aromatic evergreen shrub from the Mediterranean, celebrated for its intensely fragrant purple flower spikes and silvery-grey foliage. Highly drought-tolerant once established. Attracts bees, butterflies, and other pollinators prolifically.",
    category: ["aromatic", "medicinal", "outdoor"],
    tags: ["fragrant", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644394/lavender_aw7nws.jpg",
    care_cycle: {
      watering: {
        display: "Once a week",
        days: 7,
        method: "light",
        steps: [
          "Water deeply but infrequently — allow the top inch of soil to dry out completely before watering again",
          "Overwatering is the most common way to kill lavender — it is highly drought-tolerant and prefers slightly dry conditions",
          "During the growing season, water once a week; in cooler months, reduce to every two to three weeks",
          "Always water at soil level — wet foliage promotes fungal diseases in this Mediterranean plant",
        ],
      },
      repotting: {
        display: "Every 2–3 years",
        days: 730,
        method: "refresh",
        steps: [
          "Repot every two to three years or when roots begin growing out of the drainage holes",
          "Use a terracotta pot — its porous walls allow the soil to breathe and dry more effectively between waterings",
          "Use a sandy, well-draining mix: standard potting soil blended 50/50 with coarse sand or perlite",
          "The pot should be at least 12 to 16 inches in diameter to allow adequate root room",
        ],
      },
      fertilizing: {
        display: "Once a year",
        days: 180,
        method: "light",
        steps: [
          "Lavender is native to poor, rocky, low-fertility soil — over-fertilizing is one of the most damaging things you can do to it",
          "Apply a single slow-release, low-nitrogen balanced fertilizer in early spring — this is usually sufficient for the whole season",
          "Excess nitrogen produces a surge of soft, leafy growth at the direct expense of fragrant flower production",
          "Avoid fertilizing in autumn or winter when the plant is dormant",
        ],
      },
      pruning: {
        display: "After flowering",
        days: 180,
        method: "trim",
        steps: [
          "Prune by cutting back about one-third of each stem just after flowering ends — the single most important maintenance task for lavender",
          "Always cut back only into green growth — never cut into the old woody stems as lavender cannot regenerate from old wood",
          "Shape the plant into a neat, compact mound to prevent it from splitting open at the centre with age",
          "A second light pruning in early spring removes winter damage and helps maintain a dense, bushy form",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy well-draining",
      soil_used: "Cactus/succulent mix",
    },
    benefits: [
      "Intensely fragrant flowers used in essential oils, sachets, and herbal remedies for relaxation",
      "Attracts bees and butterflies — one of the best pollinator plants for a balcony",
      "Highly drought-tolerant once established — ideal for low-maintenance balcony growing",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Root rot from overwatering",
      "Woody sparse growth from skipping post-flower pruning",
    ],
  },
  {
    plant_id: "ashwagandha",
    plant_name: "Ashwagandha",
    scientific_name: "Withania somnifera",
    description:
      "Perennial shrub known as Indian Ginseng, one of the most important herbs in Ayurvedic medicine with over 3,000 years of documented use. The fleshy roots contain withanolides with adaptogenic and anti-inflammatory properties. Home-harvestable within 8–10 months.",
    category: ["medicinal", "outdoor", "low_maintenance"],
    tags: ["medicinal", "ayurvedic"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644420/ashwagandha_dqtojr.jpg",
    care_cycle: {
      watering: {
        display: "Every 4–5 days",
        days: 5,
        method: "light",
        steps: [
          "Water deeply but allow the soil to dry out almost completely between waterings — ashwagandha is native to dry, arid conditions and is highly drought-tolerant",
          "Check that the top 3 to 5 cm of soil are fully dry before rewatering to prevent root rot",
          "In peak summer heat, water every 3 to 4 days; in cooler months, reduce to once a week or less",
          "Use well-drained terracotta containers — plastic pots retain too much moisture for this plant's preferences",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Repot annually in early spring into a deep container at least 30 to 40 cm deep to accommodate the long taproot",
          "Use a sandy, well-draining soil blend — the plant's medicinal root compounds develop best when the roots are not waterlogged",
          "Move to a pot one size larger each season; excessively large pots hold moisture and impede root development",
          "After repotting, withhold water for 2 to 3 days to allow any damaged roots to heal before resuming normal care",
        ],
      },
      fertilizing: {
        display: "Every 6–8 weeks",
        days: 45,
        method: "organic",
        steps: [
          "Apply a balanced organic fertilizer or well-aged compost every 6 to 8 weeks during the growing season",
          "Avoid high-nitrogen synthetic fertilizers — excessive nitrogen promotes lush leafy growth at the expense of medicinal root development",
          "A light top-dressing of vermicompost or cow dung compost once a month is the traditional and most effective feeding method",
          "Do not fertilize during winter dormancy or after the plant begins to form berries",
        ],
      },
      pruning: {
        display: "Twice a year",
        days: 180,
        method: "trim",
        steps: [
          "Prune back by one-third in early spring to encourage bushy, compact growth and new lateral branching",
          "Remove any dead, dry, or crossing stems throughout the growing season using clean, sharp shears",
          "Cut back hard after harvesting the root to allow the plant to regenerate if being grown as a multi-season plant",
          "Remove any yellowing or diseased leaves promptly to maintain airflow and prevent fungal issues",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy low-fertility",
      soil_used: "Sandy loam mix",
    },
    benefits: [
      "Adaptogenic root used in Ayurveda to reduce stress, support energy levels, and improve sleep quality",
      "Withanolides in the root are extensively studied for anti-inflammatory and neuroprotective effects",
      "Home-harvestable medicinal plant producing a useful root crop within 8 to 10 months",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Root rot from overwatering or poor drainage",
      "Leaf curl from intense afternoon heat",
    ],
  },
  {
    plant_id: "brahmi",
    plant_name: "Brahmi",
    scientific_name: "Bacopa monnieri",
    description:
      "Creeping perennial herb native to Indian wetlands, revered in Ayurvedic medicine for over 3,000 years as a cognitive enhancer. Active compounds called bacosides have been clinically studied for improving memory, reducing anxiety, and protecting neurons. Requires ample moisture.",
    category: ["medicinal", "indoor", "aromatic"],
    tags: ["medicinal", "ayurvedic"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644462/brahmi_dnlzzc.jpg",
    care_cycle: {
      watering: {
        display: "Daily",
        days: 1,
        method: "deep",
        steps: [
          "Brahmi is a semi-aquatic plant — keep the soil consistently moist at all times and never allow it to dry out",
          "Water daily in warm weather, especially on sunny balconies — the plant's small succulent leaves lose moisture rapidly",
          "Can also be grown hydroponically in shallow water trays or with the pot sitting in 1 to 2 cm of water in a saucer",
          "In cooler months reduce watering frequency slightly but ensure the soil remains moist throughout",
        ],
      },
      repotting: {
        display: "Every 6–8 months",
        days: 210,
        method: "division",
        steps: [
          "Repot every 6 to 8 months as brahmi spreads quickly and fills its container with a dense mat of roots",
          "Divide the root mass and repot into multiple containers using fresh, rich, moisture-retaining potting soil",
          "Use shallow, wide containers at least 15 to 20 cm deep — the spreading root system prefers breadth over depth",
          "Refresh with organic-rich compost at each repotting to support vigorous leafy growth",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 25,
        method: "organic",
        steps: [
          "Apply a nitrogen-rich organic fertilizer or liquid compost tea every 3 to 4 weeks during the growing season",
          "Brahmi is a vigorous grower when well-nourished — regular feeding sustains the dense leafy mats used for harvest",
          "Avoid synthetic chemical fertilizers as they may reduce the concentration of medicinally active bacosides in the leaves",
          "Reduce feeding in winter when growth naturally slows",
        ],
      },
      pruning: {
        display: "Every 2–3 weeks",
        days: 18,
        method: "trim",
        steps: [
          "Harvest sprigs of 5 to 10 cm regularly — harvesting directly stimulates bushier, denser new growth",
          "Trim back any long, sprawling stems to keep the plant compact and well-shaped in its container",
          "Remove any yellowing or dead leaves promptly to maintain a healthy, dense mat",
          "Cut back by one-third in spring to refresh the plant and encourage a strong new flush of medicinal foliage",
        ],
      },
    },
    soil_type: {
      characteristics: "Moisture-retaining rich",
      soil_used: "Potting mix + cocopeat",
    },
    benefits: [
      "Bacosides in leaves clinically studied for improving memory, concentration, and reducing anxiety",
      "Revered Ayurvedic medhya rasayana — one of the most important cognitive herbs in traditional Indian medicine",
      "Fresh leaves are consumed directly or as a juice for their documented neuroprotective properties",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "partial_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Wilting from soil drying out",
      "Aphids on new growth in dry conditions",
    ],
  },
  {
    plant_id: "mogra",
    plant_name: "Mogra",
    scientific_name: "Jasminum sambac",
    description:
      "Compact evergreen flowering shrub known as Arabian Jasmine. One of the most beloved aromatic plants of Indian homes, used in religious offerings, hair garlands (gajra), weddings, and attar perfumery. Produces multiple flushes of intensely fragrant blooms year-round in warm conditions.",
    category: ["flowering", "aromatic", "outdoor"],
    tags: ["fragrant", "decorative"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644503/mogra_lsxzdf.jpg",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water when the top 1 to 2 cm of soil feel dry — mogra prefers consistently moist but never waterlogged soil",
          "Water deeply at the base of the plant, keeping the foliage dry to reduce risk of fungal disease",
          "In peak summer, container-grown mogra may need watering every day — check soil moisture daily during hot spells",
          "Reduce watering frequency in winter to once every 5 to 7 days when growth and flowering naturally slow",
        ],
      },
      repotting: {
        display: "Every 1–2 years",
        days: 365,
        method: "upgrade",
        steps: [
          "Repot every one to two years in early spring into fresh, fertile, well-draining potting mix",
          "Use a pot one size larger — slightly pot-bound plants produce more flowers than those in oversized containers",
          "Incorporate slow-release organic fertilizer or bone meal into the new potting mix at repotting time",
          "After repotting, place in a partially shaded spot for one week to reduce transplant stress before returning to full sun",
        ],
      },
      fertilizing: {
        display: "Every 2 weeks",
        days: 14,
        method: "balanced",
        steps: [
          "Feed every two weeks with a high-potassium liquid fertilizer during the main flowering season from March to October",
          "A banana peel fertilizer or potassium-rich organic liquid is a traditional and effective choice for boosting bloom production",
          "Apply a balanced NPK fertilizer (10-10-10 or similar) once a month in the off-season to maintain overall plant health",
          "Always water the soil before applying any fertilizer to prevent root burn from concentrated salts",
        ],
      },
      pruning: {
        display: "After each flush",
        days: 60,
        method: "pinch",
        steps: [
          "Prune back lightly after each flowering flush to encourage the next round of blooms — mogra flowers on new wood",
          "Remove all spent flowers and seed pods promptly to redirect energy into new bud formation",
          "In early spring, perform a harder pruning, cutting back by one-third to reshape the plant and stimulate vigorous new growth",
          "Pinch back growing tips regularly throughout the season to maintain a compact, bushy, floriferous form",
        ],
      },
    },
    soil_type: {
      characteristics: "Organically rich draining",
      soil_used: "Potting mix + compost",
    },
    benefits: [
      "Intensely fragrant blooms used in religious rituals, gajra garlands, and traditional Indian attar perfumery",
      "Flowers multiple times a year in warm Indian conditions, providing a near-continuous supply of blooms",
      "Compact and well-suited to balcony containers on any sunny Indian home",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "moderate",
    common_issues: [
      "Bud drop from inconsistent watering or low sunlight",
      "Mealybugs and spider mites — treat with neem oil",
    ],
  },
  {
    plant_id: "methi",
    plant_name: "Methi",
    scientific_name: "Trigonella foenum-graecum",
    description:
      "Annual aromatic herb known universally as Methi in Indian cooking, essential for both fresh leaves (methi bhaji) and dried seeds. One of the fastest and most rewarding crops for Indian balcony containers, with leaves harvestable within 10–15 days of sowing.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "fast growing"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644592/methi_ivdydc.jpg",
    care_cycle: {
      watering: {
        display: "Every 1–2 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water when the top inch of soil feels dry — methi prefers consistent moisture, especially during germination and early growth",
          "Young seedlings are particularly vulnerable to drying out — check containers daily in warm weather",
          "Water at the base of the plant to reduce the risk of fungal diseases in humid conditions",
          "Reduce watering once pods begin to form and the plant starts to dry down naturally towards seed maturity",
        ],
      },
      repotting: {
        display: "Each season",
        days: 90,
        method: "refresh",
        steps: [
          "Methi is an annual — sow fresh seeds directly into containers each season rather than transplanting established plants",
          "Use a container at least 15 to 20 cm deep with good drainage to support the root system",
          "Succession-sow seeds every 3 to 4 weeks for a continuous harvest of fresh leaves throughout the growing season",
          "Enrich the potting mix with compost between each sowing cycle to replenish nutrients rapidly depleted by this fast-growing crop",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 21,
        method: "organic",
        steps: [
          "Methi fixes atmospheric nitrogen through root nodules and generally does not require heavy supplemental feeding",
          "Apply a light application of liquid compost tea or diluted balanced fertilizer every 3 to 4 weeks during active growth",
          "Avoid high-nitrogen fertilizers — methi's natural nitrogen fixation means additional nitrogen primarily promotes excess leafy growth rather than quality",
          "Fresh, compost-rich potting soil at each sowing is the most effective and low-effort feeding strategy",
        ],
      },
      pruning: {
        display: "Every 1–2 weeks",
        days: 10,
        method: "pinch",
        steps: [
          "Harvest outer leaves regularly once the plant reaches 10 to 15 cm — this is the primary form of pruning for methi",
          "Pinch growing tips to delay bolting and encourage a bushier, more productive form",
          "Remove emerging flower stalks promptly to extend the leaf harvest period significantly",
          "Once the plant has fully bolted, allow seed pods to mature and dry fully before harvesting dried seeds",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile moderately moist",
      soil_used: "Potting mix + compost",
    },
    benefits: [
      "Fresh leaves and seeds are essential in Indian cooking — methi bhaji, dal methi, parathas, and spice blends",
      "Seeds contain compounds clinically studied for supporting healthy blood glucose and cholesterol levels",
      "Fastest kitchen crop for Indian balconies — leaves ready to harvest within 10 to 15 days of sowing",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_to_partial_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Bolting from heat or inconsistent watering",
      "Damping off from overwatering during germination",
    ],
  },
  {
    plant_id: "croton",
    plant_name: "Croton",
    scientific_name: "Codiaeum variegatum",
    description:
      "Bold evergreen tropical shrub with dramatically colourful foliage painted in combinations of red, orange, yellow, green, and purple. Colour intensity is directly linked to light levels. Widely grown as a balcony and verandah plant across India for its year-round ornamental impact.",
    category: ["indoor", "outdoor", "low_maintenance"],
    tags: ["decorative", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644626/croton_ue04t1.jpg",
    care_cycle: {
      watering: {
        display: "Every 3–4 days",
        days: 3,
        method: "moderate",
        steps: [
          "Water when the top 2 to 3 cm of soil feel dry — croton prefers consistently moist but never waterlogged soil",
          "Water thoroughly until it drains from the bottom, then discard excess water from the saucer to prevent root rot",
          "In hot summer conditions on a sunny balcony, check soil moisture every 2 days — the large leaves lose moisture rapidly",
          "Reduce watering frequency in winter when the plant slows — allow the top inch to dry before rewatering",
        ],
      },
      repotting: {
        display: "Every 2 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Repot every two years in spring when roots begin to emerge from drainage holes or growth visibly stalls",
          "Move to a container just one size larger — croton prefers to be moderately root-bound and overpotting causes poor leaf colour",
          "Use a well-draining, fertile potting mix; add perlite for improved aeration and drainage",
          "Handle the plant minimally during repotting — disturbing the roots can trigger a significant leaf drop",
        ],
      },
      fertilizing: {
        display: "Every 4 weeks",
        days: 30,
        method: "balanced",
        steps: [
          "Feed monthly during spring and summer with a balanced liquid fertilizer at half strength",
          "A fertilizer with a slightly higher nitrogen content encourages the lush, large, intensely coloured foliage this plant is prized for",
          "Do not over-fertilize — excess feeding produces pale, washed-out leaf colour rather than the vivid hues the plant is known for",
          "Stop feeding entirely in autumn and winter when the plant rests",
        ],
      },
      pruning: {
        display: "Every 3–4 months",
        days: 90,
        method: "shape",
        steps: [
          "Prune back leggy or overgrown stems in early spring to maintain a compact, bushy form",
          "Always use clean, sharp shears — blunt cuts damage the stems and invite disease",
          "Wear gloves when pruning — the milky white sap (latex) is a skin and eye irritant",
          "Remove any dead, pale, or fully green leaves that have lost their ornamental colour promptly",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile moisture-retaining",
      soil_used: "Potting mix + perlite",
    },
    benefits: [
      "Year-round spectacularly colourful foliage in vivid combinations of red, orange, yellow, and green",
      "Thrives in warm Indian balcony conditions — performs best in the tropical heat it evolved in",
      "One of the most impactful ornamental container plants available for Indian homes",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "bright_indirect",
    care_difficulty: "moderate",
    common_issues: [
      "Leaf drop from repotting stress or cold draughts",
      "Spider mites in dry conditions — treat with neem oil",
    ],
  },
  {
    plant_id: "adenium",
    plant_name: "Desert Rose",
    scientific_name: "Adenium obesum",
    description:
      "Striking succulent shrub also called Desert Rose, producing large trumpet-shaped blooms in deep pink, red, magenta, white, and bi-colour. Its thickened water-storing caudex is a sculptural feature. Exceptionally heat-tolerant and drought-resistant, also grown as bonsai.",
    category: ["flowering", "outdoor", "low_maintenance"],
    tags: ["decorative", "low maintenance"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773644898/desert_rose_glwb9u.jpg",
    care_cycle: {
      watering: {
        display: "Every 5–7 days",
        days: 6,
        method: "light",
        steps: [
          "Water deeply once every 5 to 7 days during the active growing season — allow the soil to dry out fully between waterings",
          "In peak summer heat with full sun exposure, check soil every 4 to 5 days — the plant grows and drinks more actively in high temperatures",
          "Drastically reduce watering in winter when the plant drops its leaves and enters dormancy — water once every 3 to 4 weeks or less",
          "Never allow the caudex base to sit in standing water — this causes irreversible rot in the swollen water-storing trunk",
        ],
      },
      repotting: {
        display: "Every 2–3 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Repot every 2 to 3 years in spring just as new growth begins, when roots visibly crowd the container",
          "Use a wide, shallow pot to showcase the sculptural caudex and provide stable drainage",
          "Use a dedicated cactus and succulent mix or blend standard potting soil 50/50 with coarse sand and perlite",
          "After repotting, wait 7 to 10 days before watering to allow any damaged roots to callous over and heal",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 21,
        method: "balanced",
        steps: [
          "Feed every 3 to 4 weeks during active growth with a low-nitrogen, high-phosphorus and potassium fertilizer to maximise flowering",
          "A bloom booster with an NPK ratio such as 10-50-10 applied in spring and summer produces spectacular results",
          "Avoid high-nitrogen formulas — they promote leafy growth at the expense of flowers",
          "Do not fertilize during winter dormancy when the plant has dropped its leaves and is resting",
        ],
      },
      pruning: {
        display: "Early spring",
        days: 180,
        method: "shape",
        steps: [
          "Prune back leggy or uneven stems in early spring just before new growth flushes — adenium blooms on new growth tips",
          "Wear gloves when pruning — the milky white sap is toxic and a skin and eye irritant",
          "Shape the plant to expose the sculptural caudex and maintain a well-balanced, compact canopy",
          "Stem cuttings removed during pruning can be left to dry for a week and then planted to propagate new plants",
        ],
      },
    },
    soil_type: {
      characteristics: "Sandy fast-draining",
      soil_used: "Cactus/succulent mix",
    },
    benefits: [
      "Large, vivid trumpet-shaped blooms produced prolifically throughout the hot Indian summer season",
      "Exceptionally heat and drought-tolerant — thrives in the intense conditions that challenge other balcony plants",
      "Sculptural caudex base makes it an outstanding ornamental specimen and bonsai subject",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Caudex rot from overwatering or poor drainage",
      "No blooms from insufficient direct sunlight",
    ],
  },
  {
    plant_id: "aparajita",
    plant_name: "Aparajita",
    scientific_name: "Clitoria ternatea",
    description:
      "Vigorous fast-growing perennial climbing vine known as Aparajita or Shankhpushpi. Celebrated for its intense butterfly-shaped blue flowers used as natural food dye and in Blue Pea tea. Documented Ayurvedic uses for cognitive function and memory. One of the most rewarding climbers for a sunny Indian balcony trellis.",
    category: ["flowering", "medicinal", "outdoor"],
    tags: ["decorative", "medicinal"],
    image_name: "aparajita",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water when the top inch of soil feels dry — aparajita prefers consistently moist but not waterlogged soil",
          "Water deeply at the base of the plant and avoid wetting the foliage to prevent fungal disease in humid conditions",
          "In peak summer heat, check soil daily — container plants on sunny balconies may need watering every 2 days",
          "Reduce watering frequency in winter to once every 5 to 7 days when growth naturally slows",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "upgrade",
        steps: [
          "Repot annually in spring into a larger container with fresh, fertile potting mix",
          "Use a deep container at least 30 cm wide with a trellis, bamboo canes, or railing for the vine to climb",
          "Mix compost into the potting soil at repotting time — aparajita is a legume and also enriches the soil with fixed nitrogen",
          "Position the trellis support in the pot at planting time to avoid disturbing roots later",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 21,
        method: "balanced",
        steps: [
          "Apply a balanced liquid fertilizer every 3 to 4 weeks during the growing season from spring through autumn",
          "As a legume, aparajita fixes its own atmospheric nitrogen — avoid very high-nitrogen feeds that can reduce flowering",
          "Switch to a high-potassium, low-nitrogen formula when buds begin to form to maximise flower production",
          "A single application of bone meal at the start of the growing season provides sustained phosphorus for abundant blooming",
        ],
      },
      pruning: {
        display: "After flowering",
        days: 90,
        method: "trim",
        steps: [
          "Trim back overgrown or tangled stems after each main flowering flush to encourage fresh, vigorous new growth",
          "In early spring, cut back the entire vine by one-third to one-half to reshape and prevent woody bare stems at the base",
          "Remove spent flowers and seed pods regularly — this redirects energy into continuous new bud formation",
          "The vine can be cut back hard if it has overgrown its trellis — it recovers quickly from hard pruning",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Potting mix + compost",
    },
    benefits: [
      "Striking vivid blue flowers that produce a natural food-safe blue dye used in Blue Pea tea and South Asian cooking",
      "Documented Ayurvedic cognitive adaptogen — studied for supporting memory and reducing anxiety",
      "Fast-growing balcony climber that provides ornamental cover for railings and trellises within weeks",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Fungal leaf spot from overhead watering or poor airflow",
      "Reduced flowers from excess nitrogen or low sunlight",
    ],
  },
  {
    plant_id: "neem",
    plant_name: "Neem",
    scientific_name: "Azadirachta indica",
    description:
      "Fast-growing evergreen tree known as Sarva Roga Nivarini in Sanskrit. Every part has documented medicinal, pesticidal, and cosmetic applications. The active compound azadirachtin is one of the most effective natural insecticides known. Dwarf container varieties thrive on sunny Indian balconies.",
    category: ["medicinal", "outdoor", "low_maintenance"],
    tags: ["medicinal", "pest repellent"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773645479/neem_plant_ddk99b.jpg",
    care_cycle: {
      watering: {
        display: "Every 3–5 days",
        days: 4,
        method: "moderate",
        steps: [
          "Water when the top 3 to 5 cm of soil feel dry — neem is drought-tolerant once established and prefers to dry between waterings",
          "Young plants in containers require more consistent moisture than established trees — check soil every 3 days in summer",
          "Water deeply and thoroughly until it drains from the bottom, then discard excess to prevent waterlogging",
          "In winter, reduce watering significantly to once a week or less as growth slows considerably",
        ],
      },
      repotting: {
        display: "Every 2 years",
        days: 730,
        method: "upgrade",
        steps: [
          "Repot container neem every two years in spring as the tree is fast-growing and quickly outgrows its pot",
          "Use a large, deep container at least 40 to 50 cm wide and deep to accommodate the extensive root system",
          "Use a well-draining mix of garden soil, compost, and coarse sand — neem grows in poor, dry soils in the wild",
          "Prune back the canopy by 15 to 20% when repotting to reduce transplant stress and maintain container-appropriate size",
        ],
      },
      fertilizing: {
        display: "Every 6–8 weeks",
        days: 56,
        method: "organic",
        steps: [
          "Apply a balanced slow-release organic fertilizer or composted cow manure every 6 to 8 weeks during spring and summer",
          "Neem grows naturally in poor soils and does not require heavy feeding — the focus should be on soil health rather than nutrient loading",
          "A top-dressing of vermicompost once every 2 months is the most practical and effective approach for container plants",
          "Do not fertilize in winter — neem slows significantly and fertilizing during this period produces weak, tender growth",
        ],
      },
      pruning: {
        display: "Early spring",
        days: 180,
        method: "shape",
        steps: [
          "Prune in early spring to maintain a compact, container-appropriate size — without pruning, neem grows rapidly into a large tree",
          "Cut back the main leader and lateral branches by one-third to one-half to control height and encourage a dense canopy",
          "Remove any dead, crossing, or inward-growing branches to maintain good airflow and reduce disease risk",
          "Harvest leaves for home use throughout the growing season — regular harvesting naturally controls size while providing useful material",
        ],
      },
    },
    soil_type: {
      characteristics: "Well-draining alkaline",
      soil_used: "Soil + compost + sand",
    },
    benefits: [
      "Every part of the tree has documented medicinal, pesticidal, and cosmetic Ayurvedic applications",
      "Neem oil from seeds is one of the most effective natural organic pesticides available",
      "Leaves used in traditional medicine for skin health, immunity support, and as a natural antimicrobial",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Rapid overgrowth without regular pruning",
      "Yellow leaves from overwatering or poor drainage",
    ],
  },
  {
    plant_id: "periwinkle",
    plant_name: "Sadabahar",
    scientific_name: "Catharanthus roseus",
    description:
      "Perennial flowering herb known as Sadabahar meaning 'always blooming'. One of the most medically important plants in the world — vincristine and vinblastine extracted from its leaves are used as frontline chemotherapy drugs. Blooms continuously year-round in warm Indian conditions.",
    category: ["flowering", "medicinal", "outdoor"],
    tags: ["decorative", "medicinal"],
    image_name: "periwinkle",
    care_cycle: {
      watering: {
        display: "Every 3–4 days",
        days: 3,
        method: "moderate",
        steps: [
          "Water when the top 2 cm of soil feel dry — sadabahar prefers consistently moist but not waterlogged soil",
          "Water deeply at soil level and avoid wetting the foliage to prevent fungal leaf diseases",
          "In peak Indian summer heat, check container soil every 2 days — this plant drinks more than expected in high temperatures",
          "Reduce watering frequency in cooler months to once every 5 to 7 days when growth and flowering slow slightly",
        ],
      },
      repotting: {
        display: "Yearly",
        days: 365,
        method: "refresh",
        steps: [
          "Repot annually in early spring into fresh potting mix — sadabahar performs best with refreshed soil each season",
          "Use a pot at least 20 to 25 cm wide with good drainage holes to support the fibrous root system",
          "A potting mix of 50% compost and 50% garden soil provides the nutrient-rich but well-drained medium this plant prefers",
          "Cut back the plant by one-third when repotting to stimulate a strong flush of new growth and flowers",
        ],
      },
      fertilizing: {
        display: "Every 3–4 weeks",
        days: 21,
        method: "balanced",
        steps: [
          "Feed every 3 to 4 weeks with a balanced liquid fertilizer during the active growing season",
          "A high-phosphorus formula applied monthly encourages the generous, near-continuous flowering this plant is named for",
          "Mustard cake liquid fertilizer applied every 15 days is a traditional Indian organic approach that produces excellent results",
          "Reduce feeding in the cooler months but do not stop entirely as sadabahar continues to flower through mild Indian winters",
        ],
      },
      pruning: {
        display: "Every 4–6 weeks",
        days: 35,
        method: "pinch",
        steps: [
          "Pinch back growing tips every 4 to 6 weeks to maintain a compact, bushy form and encourage continuous flowering",
          "Deadhead spent flowers regularly to redirect energy from seed production back into new bud formation",
          "Cut back the entire plant by one-third in early spring or after any period of reduced vigour to stimulate a fresh flush",
          "Remove yellowing or diseased leaves promptly to maintain good airflow and plant health",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile well-draining",
      soil_used: "Compost + garden soil",
    },
    benefits: [
      "Continuous near-year-round flowering in warm Indian conditions — one of the longest-blooming balcony plants available",
      "Leaves contain vincristine and vinblastine — among the most important chemotherapy compounds in modern medicine",
      "Exceptionally heat-tolerant and thrives on hot Indian balconies where other flowering plants decline",
    ],
    pet_friendly: false,
    toxic: true,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Fungal leaf spot or root rot from overhead watering",
      "Leggy growth from insufficient sunlight",
    ],
  },
  {
    plant_id: "lemongrass",
    plant_name: "Lemongrass",
    scientific_name: "Cymbopogon citratus",
    description:
      "Tall clump-forming perennial grass widely used in Asian cooking and Ayurvedic preparations. Its citral-rich essential oil is a proven natural mosquito repellent. Grows vigorously in containers on sunny Indian balconies, forming impressive clumps that can be regularly divided and harvested.",
    category: ["medicinal", "aromatic", "outdoor"],
    tags: ["edible", "fragrant"],
    image_name: "https://res.cloudinary.com/dcqzfrjii/image/upload/v1773645586/lemongrass_emkyek.jpg",
    care_cycle: {
      watering: {
        display: "Every 2–3 days",
        days: 2,
        method: "moderate",
        steps: [
          "Water when the top 2 to 3 cm of soil feel dry — lemongrass prefers consistently moist but not waterlogged soil",
          "Container-grown plants on sunny balconies dry quickly in summer — check soil every 2 days during hot weather",
          "Water deeply at the base of the clump to reach the fibrous root system; shallow watering causes root stress in this large plant",
          "Reduce watering in winter when growth slows — allow the top inch of soil to dry between waterings",
        ],
      },
      repotting: {
        display: "Every 1–2 years",
        days: 365,
        method: "division",
        steps: [
          "Repot or divide every 1 to 2 years when the clump becomes visibly crowded or roots begin to emerge from drainage holes",
          "Use a large, deep container at least 30 to 40 cm wide — lemongrass forms a robust clump and requires adequate space",
          "At division time, separate the clump into sections of 3 to 5 stalks each, each with a healthy root mass attached",
          "Repot into fresh, fertile, well-draining potting mix enriched with compost for vigorous new growth",
        ],
      },
      fertilizing: {
        display: "Every 4–6 weeks",
        days: 35,
        method: "balanced",
        steps: [
          "Apply a balanced nitrogen-rich liquid fertilizer every 4 to 6 weeks during spring and summer to support vigorous leaf and stalk production",
          "A fertilizer with an NPK ratio favouring nitrogen such as 20-10-10 encourages the lush, aromatic growth this plant is harvested for",
          "Organic options including diluted compost tea or liquid seaweed fertilizer are effective and preserve the essential oil content of the leaves",
          "Reduce fertilizing to once every 2 months in winter when growth slows",
        ],
      },
      pruning: {
        display: "Every 4–6 weeks",
        days: 35,
        method: "trim",
        steps: [
          "Harvest outer stalks by cutting at the base when they reach 30 to 45 cm tall — this is the primary method of managing and harvesting the plant",
          "Trim the top third of the leaf blades every 4 to 6 weeks to prevent the clump from becoming excessively tall on a balcony",
          "Remove any dry, brown, or dead outer leaves and stalks throughout the season to maintain a neat, healthy clump",
          "Cut the entire clump back to 15 to 20 cm in early spring to stimulate a fresh flush of vigorous new growth",
        ],
      },
    },
    soil_type: {
      characteristics: "Fertile moderately moist",
      soil_used: "Rich potting mix",
    },
    benefits: [
      "Essential aromatic culinary herb used in South Indian, Thai, and Vietnamese cooking and in kadha herbal teas",
      "Citral-rich essential oil is a proven natural mosquito repellent — an invaluable asset on Indian balconies",
      "Ayurvedic herb for supporting digestion, reducing fever, and promoting relaxation in herbal preparations",
    ],
    pet_friendly: true,
    toxic: false,
    light_required: "full_sunlight",
    care_difficulty: "easy",
    common_issues: [
      "Rust fungus from overhead watering in high humidity",
      "Clump overcrowding — divide every 1 to 2 years",
    ],
  },
];
